language: node_js
node_js: 16
branches:
  only: main
cache:
  npm: false
  directories:
    - '.yarn/cache'
deploy:
  fqdn: charlesstover.com
  keep-history: true
  local-dir: build
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  github-token:
    secure: gsLWTqoswbacN5IXXeT7Bt34+Jug/vTu5VsT0yv9/XKiEgmNkgxTXaaPUL+UcTPTRT3wOx6kSZ94qnHlNIlOaxcGHAsgAGN4UWC82U/2+J/HcmXsH6roRnVab0criEvXE/sLEgJiwukIwpy8Jk/2q8du60W0y4++McWdHexkg/UYoQDAIpGzeOz4HuabubZwwjrImZ1t6kgCpVinv5rnNElw/4ui3Uwz7y/70sQvolLmwfg0irrl/SdUp/4vpLCnvuYU5RBgqLcSR9qdCs7mp+07UBHzzqAJs/PAOVx9RRXYQgiy3CsDYeRKx3zhpvs0Wvk7KpTP4ufr67j1hfynuYnWZ9zg7vU0VwjWo5jLWA5ydmSVHp9dnS9IbKmqtX7DHmjv8cDk9ZzoZFyrhwmDYqPg8tSIhGw22FINy4PPDF1wpV13ZR6fBVPF3/JTd+Ifiv59kdWLaCqcKGPsN9rcKRjUuW3nMZdHHJ5hmljYYMZmPGEtlVutXyuKctnR357obCeodmtS/M58ZaiCGsZ6WBaMM63TND1Mlf7bd6dj53IIRjCd+9vGTu/4mMuPZ7jPUPhyNlZSwaN4OWmQPg3U8XRYdMbcusTz/D4ZbT89urPAaF8Z/WYvUq5ZnS9Q6SfpxmEtR89d5TUV/SDN8Ix95hpNF2fpEqr4p87vza9Bl5E=
  on:
    branch: main
install:
  - yarn
script:
  - CI=false yarn build
