logFilters:
  - code: YN0060
    level: discard

packageExtensions:
  "@awsui/component-toolkit@*":
    peerDependencies:
      react-dom: "*"
      tslib: ^2.3.0
  "@cloudscape-design/component-toolkit@*":
    peerDependencies:
      react-dom: "*"
      tslib: ^2.3.0
  "@cypress/code-coverage@*":
    dependencies:
      "@babel/preset-env": ">=7.0.0"
      babel-loader: ">=7.0.0"
      webpack: ">=4"
    peerDependencies:
      "@babel/core": ">=7.0.0"
  "@opentelemetry/context-zone@*":
    peerDependencies:
      "@opentelemetry/api": ^1.0.0
  charlesstover.com@*:
    dependencies:
      bluebird: ^3.7.0
      minimist: ^1.2.0
      semver: ^7.5.0
  cypress@*:
    dependencies:
      "@cypress/request": ^2.88.0
    peerDependencies:
      bluebird: ^3.7.0
      cachedir: ^2.3.0
      minimist: ^1.2.0
      semver: ^7.5.0
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": ">=7.0.0"
      "@babel/plugin-transform-react-jsx": ">=7.0.0"
  node-abi@*:
    peerDependencies:
      semver: ^7.5.0
  react-scripts@*:
    peerDependencies:
      sass: ">=1.0.0"
  recharts@*:
    dependencies:
      prop-types: ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.2.cjs
