yarnPath: .yarn/releases/yarn-3.1.1.cjs

# Workaround for `babel-preset-react-app` missing a dependency in its
#   `package.json` file.
# https://github.com/facebook/create-react-app/issues/11793
packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
