logFilters:
  - code: YN0060
    level: discard

packageExtensions:
  "@awsui/component-toolkit@1.0.0":
    peerDependencies:
      tslib: ^2.3.1
  "@cloudscape-design/component-toolkit@1.0.0":
    peerDependencies:
      tslib: ^2.3.1
  "@cypress/code-coverage@3.10.4":
    dependencies:
      "@babel/preset-env": ">=7.0.0"
      babel-loader: ">=7.0.0"
      webpack: ">=4"
    peerDependencies:
      "@babel/core": ">=7.0.0"
  "@opentelemetry/context-zone@1.12.0":
    peerDependencies:
      "@opentelemetry/api": ^1.0.0
  aws-rum-web@1.13.6:
    dependencies:
      "@aws-sdk/querystring-builder": ^3.36.0
  charlesstover.com@*:
    dependencies:
      bluebird: ^3.7.2
  cypress@12.11.0:
    dependencies:
      minimist: ^1.2.8
      semver: ^7.3.2
    peerDependencies:
      bluebird: ^3.7.2
  eslint-config-react-app@7.0.1:
    dependencies:
      "@babel/plugin-syntax-flow": ">=7.0.0"
      "@babel/plugin-transform-react-jsx": ">=7.0.0"
  react-scripts@*:
    peerDependencies:
      sass: ">=1.0.0"
  recharts@2.5.0:
    dependencies:
      prop-types: ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
