logFilters:
  - code: YN0060
    level: discard

packageExtensions:
  "@cypress/code-coverage@*":
    peerDependencies:
      "@babel/core": ">=7.0.0"
      "@babel/preset-env": ">=7.0.0"
      babel-loader: ">=7.0.0"
      istanbul-lib-coverage: ^3.0.0
      webpack: ">=4"
  # https://github.com/aws-observability/aws-rum-web/issues/328
  aws-rum-web@*:
    dependencies:
      "@aws-sdk/querystring-builder": ^3.0.0
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": ">=7.0.0"
      "@babel/plugin-transform-react-jsx": ">=7.0.0"
  react-scripts@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": ">=7.0.0"
      "@babel/plugin-transform-react-jsx": ">=7.0.0"
      sass: ">=1.0.0"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
