compatibility_date = "2023-10-30"
kv_namespaces = [{ binding = "AUTHN_USER_IDS", id = "AUTHN_USER_IDS" }]
main = "src/index.ts"
name = "quisido-whoami-dev"
tsconfig = "./tsconfig.json"

[dev]
local_protocol = "https"
port = 1098              # parseInt('whoami', 36) % 9999

[env.production]
name = "quisido-whoami"

kv_namespaces = [
  { binding = "AUTHN_USER_IDS", id = "4dca15c74cdb4fba9680ee52d46c1534", preview_id = "235afbbf5e6a4a6bbadf56ea33d07b3e" },
]

[env.production.vars]
COOKIE_DOMAIN = "quisi.do"
ENVIRONMENT_NAME = "production"

[env.staging]
name = "quisido-whoami-staging"
workers_dev = true

kv_namespaces = [
  { binding = "AUTHN_USER_IDS", id = "235afbbf5e6a4a6bbadf56ea33d07b3e" },
]

[env.staging.vars]
COOKIE_DOMAIN = "localhost"
ENVIRONMENT_NAME = "staging"

[placement]
mode = "smart"
