compatibility_date = "2023-10-30"
main = "src/index.ts"
name = "authn"
tsconfig = "./tsconfig.json"
workers_dev = true

d1_databases = [
  { binding = "AUTHN", database_id = "d0e825fc-b58d-49b3-a86c-a9d967278d80", database_name = "authn", database_preview_id = "768ff4ca-4c33-4c2c-bd62-24afe6e2bb13" },
]

kv_namespaces = [
  { binding = "AUTHN_USER_IDS", id = "4dca15c74cdb4fba9680ee52d46c1534" },
]

[dev]
ip = "127.0.0.1"
port = 5882      # parseInt('authn', 36) % 9999

[placement]
mode = "smart"
