name: CharlesStover.com

jobs:
  install-yarn:
    name: Install Node dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable

  build:
    name: Build
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn packages/charlesstover.com run build
        env:
          # Ignore warnings from `mini-css-extract-plugin`.
          CI: false
          REACT_APP_GITHUB_REPOSITORY: ${{ github.repository }}
          REACT_APP_GITHUB_SHA: ${{ github.sha }}
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--build
          path: packages/charlesstover.com/build/

  cypress:
    needs: install-yarn
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: End-to-end test
        uses: cypress-io/github-action@v4
        env:
          CHOKIDAR_USEPOLLING: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYC_REPORT_DIR: cypress/coverage/${{ matrix.os }}-${{ matrix.browser }}-${{ matrix.container }}
          REACT_APP_GITHUB_REPOSITORY: ${{ github.repository }}
          REACT_APP_GITHUB_SHA: ${{ github.sha }}
        with:
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}
          command-prefix: yarn dlx
          config-file: cypress.config.cjs
          group: ${{ matrix.os }}-${{ matrix.browser }}
          parallel: true
          project: packages/charlesstover.com
          record: true
          start: yarn packages/charlesstover.com run cypress:start
          tag: ${{ github.event_name }}
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 300
      - name: Upload coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--cypress--coverage
          path: packages/charlesstover.com/coverage/
      - name: Upload screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--cypress--screenshots
          path: packages/charlesstover.com/cypress/screenshots/
      - name: Upload videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--cypress--videos
          path: packages/charlesstover.com/cypress/videos/
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        browser: [chrome, edge] # firefox
        container: [1, 2]
        exclude:
          - browser: edge
            os: ubuntu

  eslint:
    name: ESLint
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn packages/charlesstover.com run eslint

  jest:
    name: Jest
    needs: install-yarn
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_HOSTNAME: none
          DD_INSIDE_CI: true
        ports:
          - 8126:8126
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Unit test
        run: yarn packages/charlesstover.com run jest
        env:
          DD_ENV: ci
      - name: Upload coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--jest--coverage
          path: packages/charlesstover.com/jest/coverage/

  coverage:
    name: Coverage
    needs: [cypress, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Cypress coverage
        uses: actions/download-artifact@v3
        with:
          name: charlesstover-com--cypress--coverage
          path: packages/charlesstover.com/cypress/coverage/
      - name: Download Jest coverage
        uses: actions/download-artifact@v3
        with:
          name: charlesstover-com--jest--coverage
          path: packages/charlesstover.com/jest/coverage/
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Report coverage
        run: yarn packages/charlesstover.com run coverage
        env:
          BRANCHES_COVERAGE_THRESHOLD: 1
          FUNCTIONS_COVERAGE_THRESHOLD: 1
          LINES_COVERAGE_THRESHOLD: 1
          STATEMENTS_COVERAGE_THRESHOLD: 1
      - name: Upload coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: charlesstover-com--coverage
          path: |
            packages/charlesstover.com/.nyc_output/
            packages/charlesstover.com/coverage/

  github-pages:
    name: GitHub Pages
    if: ${{ github.event_name == 'push' }}
    needs: [build, coverage, cypress, eslint, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: charlesstover-com--build
          path: packages/charlesstover.com/build/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          clean: true
          folder: packages/charlesstover.com/build/
          single-commit: true

  sentry-release:
    if: ${{ github.event_name == 'push' }}
    needs: [build, coverage, cypress, eslint, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: charlesstover-com--build
          path: packages/charlesstover.com/build/
      - name: Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: info
          SENTRY_ORG: charles-stover
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: build
          version: ${{ github.sha }}

  cloudflare-purge:
    if: ${{ github.event_name == 'push' }}
    needs: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare files
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: >
          curl \
            --data '{
              "files": [
                "https://charlesstover.com",
                "https://charlesstover.com/index.html"
              ]
            }' \
            --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --header "Content-Type:application/json" \
            --request POST \
            "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache"

on:
  pull_request:
  push:
    branches: [main]
