name: Pull request

jobs:
  install-yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Install dependencies
        run: yarn install --immutable

  build:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
        env:
          # Ignore warnings from `mini-css-extract-plugin`.
          CI: false
          REACT_APP_GITHUB_REPOSITORY: ${{ github.repository }}
          REACT_APP_GITHUB_SHA: ${{ github.sha }}
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  eslint:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Install dependencies
        run: yarn install --immutable
      - name: ESLint
        run: yarn eslint

  install-cypress:
    needs: install-yarn
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Install dependencies
        run: yarn install --immutable
      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
    strategy:
      matrix:
        os: [ubuntu, windows]

  jest:
    needs: install-yarn
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_HOSTNAME: none
          DD_INSIDE_CI: true
        ports:
          - 8126:8126
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Install dependencies
        run: yarn install --immutable
      - name: Jest
        run: yarn jest
        env:
          DD_ENV: ci
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: jest/coverage

  cypress:
    needs: install-cypress
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: latest
      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          CHOKIDAR_USEPOLLING: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          DEBUG: '@cypress/github-action'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_GITHUB_REPOSITORY: ${{ github.repository }}
          REACT_APP_GITHUB_SHA: ${{ github.sha }}
        with:
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.event_name }}-${{ github.sha }}
          command-prefix: yarn dlx
          group: ${{ matrix.os }}-${{ matrix.browser }}
          install-command: yarn install --immutable
          parallel: true
          record: true
          start: yarn start
          tag: ${{ github.event_name }}
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 120
    strategy:
      fail-fast: false
      matrix:
        browser: [edge, firefox, chrome]
        # Re-add `windows` when GitHub Actions fixes the bug:
        #   Could not find a Cypress configuration file, exiting.
        #   We looked but did not find a "cypress.json" file in this folder:
        #     D:\a\charlesstover.com\charlesstover.com
        # https://github.com/CharlesStover/charlesstover.com/runs/4183485790?check_suite_focus=true
        os: [ubuntu]
        _containers: [1, 2, 3]
        exclude:
          - browser: edge
            os: ubuntu

  sentry-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: info
          SENTRY_ORG: charles-stover
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: beta
          sourcemaps: build
          version: ${{ github.sha }}

on:
  pull_request:
    branches: [main]
