name: Push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn

  cypress:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_INSTALL_BINARY: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: yarn cypress
          install-command: yarn
          record: true
          start: yarn start
          tag: ${{ github.event_name }}
          wait-on: 'http://localhost:3000'

  eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: ESLint
        run: yarn eslint

  jest:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: Jest
        run: yarn jest

  sentry:
    needs: [cypress, eslint, jest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production

on:
  push:
    branches: [main]
